import 'package:freezed_annotation/freezed_annotation.dart';

part 'billable_info_level_model.freezed.dart';
part 'billable_info_level_model.g.dart';

@freezed
class BillableInfoLevelModel with _$BillableInfoLevelModel {
  const factory BillableInfoLevelModel({
    int? billable_id,
    int? billable_subscription_id,
    String? billable_subscription_public_name,
    String? billable_type,
    int? billable_book_id,
    int? billable_job_id,
    bool? billable_islocked,
    DateTime? billable_created,
    DateTime? billable_updated,
    bool? billable_isdraft,
    bool? billable_isfixed,
    bool? billable_isdeleted,
    Map<String, String>? recordlock,
    dynamic billable_synced_invoice_number,
    String? billable_accounting_provider_name,
    dynamic billable_accounting_provider_name_display,
    bool? billable_use_nm_invoice_numbers,
    bool? billable_prompt_to_sync_invoices_on_send,
    String? billable_tax_name,
    bool? billable_hide_billable_totals,
    String? billable_associated_record_type,
    int? billable_associated_record_id,
    String? billable_associated_record_number,
    String? billable_associated_record_name,
    String? billable_job_number,
    String? billable_job_name,
    String? billable_job_order_number,
    String? billable_book_number,
    String? billable_book_summary,
    int? billable_book_job_id,
    String? billable_book_job_order_number,
    int? book_client_contact_id,
    String? book_client_contact_name,
    @Default([]) List<BillableInfoLevelItem> billableItems,
  }) = _BillableInfoLevelModel;

  factory BillableInfoLevelModel.fromJson(Map<String, Object?> json) =>
      _$BillableInfoLevelModelFromJson(json);
}

@freezed
class BillableInfoLevelItem with _$BillableInfoLevelItem {
  const factory BillableInfoLevelItem({
    int? billable_id,
    String? billable_type,
    int? billable_subscription_id,
    String? billable_subscription_public_name,
    DateTime? billable_created,
    DateTime? billable_updated,
    String? billable_number,
    double? billable_total,
    double? billable_invoiced_total,
    double? billable_not_billable_total,
    double? billable_invoiced_amount_remaining_total,
    bool? billable_issent,
    DateTime? billable_date_last_sent,
    int? billable_client_contact_id,
    String? billable_client_contact_name,
    int? billable_createdby_contact_id,
    String? billable_createdby_contact_name,
    String? billable_accounting_provider_name,
    bool? billable_use_nm_invoice_numbers,
    DateTime? billable_date_due,
    DateTime? billable_date,
    bool? billable_is_added_to_charges,
    bool? billable_has_files,
    int? billableitem_id,
    dynamic billableitem_uid,
    int? billableitem_billable_id,
    int? billableitem_billablesection_id,
    int? billableitem_subscription_id,
    int? billableitem_order,
    int? billableitem_billable_book_id,
    String? billableitem_billable_book_number,
    String? billableitem_billable_book_summary,
    int? billableitem_billable_job_id,
    String? billableitem_billable_job_number,
    String? billableitem_billable_job_name,
    bool? billableitem_istime,
    bool? billableitem_isproduct,
    bool? billableitem_isdisbursement,
    double? billableitem_quantity,
    int? billableitem_saleitem_id,
    String? billableitem_name,
    String? billableitem_code,
    String? billableitem_supplier_code,
    String? billableitem_description,
    double? billableitem_buy_price,
    double? billableitem_actual_buy_price,
    double? billableitem_sell_price,
    double? billableitem_actual_sell_price,
    double? billableitem_list_buy_price,
    double? billableitem_list_sell_price,
    DateTime? billableitem_list_price_date,
    double? billableitem_buy_discount_rate,
    double? billableitem_sell_discount_rate,
    double? billableitem_markup_rate,
    double? billableitem_buy_subtotal,
    double? billableitem_sell_subtotal,
    String? billableitem_unit_string,
    String? billableitem_currency,
    int? billableitem_taxrate_id,
    double? billableitem_taxrate_rate,
    bool? billableitem_taxrate_is_valid,
    List<dynamic>? billableitem_saleitem_categories,
    int? billableitem_supplier_contact_id,
    String? billableitem_supplier_contact_name,
    bool? billableitem_is_from_hardware_provider,
    bool? billableitem_is_locally_saved_product,
    DateTime? billableitem_start,
    dynamic billableitem_start_address,
    dynamic billableitem_start_location,
    DateTime? billableitem_end,
    dynamic billableitem_end_address,
    dynamic billableitem_end_location,
    bool? billableitem_istime_range,
    bool? billableitem_isactual_times,
    bool? billableitem_isbillable,
    bool? billableitem_ismanually_invoiced,
    dynamic billableitem_manual_invoice_id,
    dynamic billableitem_manual_invoice_number,
    DateTime? billableitem_manual_invoice_date,
    String? billableitem_type,
    bool? billableitem_islinked,
    int? billableitem_source_billableitem_id,
    int? billableitem_source_billableitem_billable_id,
    dynamic billableitem_source_billableitem_billable_type,
    dynamic billableitem_source_billableitem_billable_number,
    dynamic billableitem_ordered_total,
    double? billableitem_invoiced_total,
    List<TargetBillableitemSummary>? target_billableitem_summaries,
    String? billableitem_created_by_contact_name_display,
    DateTime? billableitem_created_date,
    String? billableitem_updated_by_contact_name_display,
    DateTime? billableitem_updated_date,
    int? billableitem_contact_id,
    String? billableitem_contact_name_display,
    String? billableitem_entry_type,
    bool? billableitem_isexcluded_timesheet_entry,
    dynamic billableitem_is_length_breakdown,
    List<dynamic>? lengthBreakdowns,
  }) = _BillableInfoLevelItem;

  factory BillableInfoLevelItem.fromJson(Map<String, Object?> json) =>
      _$BillableInfoLevelItemFromJson(json);
}

@freezed
class TargetBillableitemSummary with _$TargetBillableitemSummary {
  const factory TargetBillableitemSummary({
    int? billableitem_id,
    double? billableitem_subtotal,
    int? billableitem_billable_id,
    String? billableitem_billable_type,
    String? billableitem_billable_number,
    DateTime? billableitem_billable_date,
  }) = _TargetBillableitemSummary;

  factory TargetBillableitemSummary.fromJson(Map<String, Object?> json) =>
      _$TargetBillableitemSummaryFromJson(json);
}
