import 'package:api_service/src/models/jobs/actual_charges.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'task_info_level_model.freezed.dart';
part 'task_info_level_model.g.dart';

@freezed
class TaskInfoLevelModel with _$TaskInfoLevelModel {
  const factory TaskInfoLevelModel({
    @JsonKey(name: 'ETag') String? e_tag,
    int? book_id,
    String? book_key,
    String? book_number,
    String? book_summary,
    String? book_details,
    DateTime? book_start,
    DateTime? book_end,
    bool? book_isallday,
    bool? book_isactual_times,
    String? book_address,
    bool? bookcont_is_assigned,
    dynamic book_address_coords,
    bool? book_islocked,
    int? book_importance,
    String? book_importance_name,
    int? book_priority_id,
    String? book_priority_name,
    String? book_priority_brush_colour_argb,
    int? book_usercategory_id,
    String? book_usercategory_name,
    String? book_usercategory_brush_colour_argb,
    int? book_job_id,
    dynamic book_job_code,
    String? book_job_number,
    String? book_job_order_number,
    String? book_job_name,
    bool? book_job_is_internal,
    int? book_job_client_contact_id,
    String? book_job_client_contact_name,
    String? book_job_client_contact_email,
    String? book_job_client_contact_phone_mobile,
    int? book_client_contact_id,
    String? book_client_contact_name,
    String? book_client_contact_email,
    String? book_client_contact_phone_mobile,
    int? book_site_contact_id,
    String? book_site_contact_name,
    int? book_subscription_id,
    String? book_subscription_name,
    bool? book_is_recurring,
    bool? book_is_exception,
    bool? book_isrecurring,
    bool? book_isexception,
    bool? book_isoccurrence,
    String? book_recurrence_pattern,
    String? book_recurrence_text,
    DateTime? book_recurrence_start,
    DateTime? book_recurrence_end,
    String? book_time_zone,
    int? book_master_book_id,
    dynamic book_first_occurrence_key,
    int? book_bookingstatus_id,
    String? book_bookingstatus_name,
    String? book_bookingstatus_brush_colour_argb,
    bool? is_owner,
    @JsonKey(name: 'BookingContacts')
    @Default([])
        List<BookingContact> bookingContacts,
    int? book_created_by_contact_id,
    String? book_created_by_contact_name_display,
    String? book_created_by_contact_email,
    String? book_created_by_contact_phone_mobile,
    DateTime? book_created_date,
    int? book_updated_by_contact_id,
    String? book_updated_by_contact_name_display,
    String? book_updated_by_contact_email,
    String? book_updated_by_contact_phone_mobile,
    DateTime? book_updated_date,
    bool? book_isdeleted,
    ActualChargesTotals? actual_charges_totals,
    double? book_actual_charges_subtotal,
    bool? book_istemplate,
    bool? book_iscomplete,
    bool? book_is_displayed_on_timeline,
    double? book_progress,
    bool? book_has_back_costing_link,
    dynamic book_linked_quote_id,
    String? book_linked_quote_name,
    dynamic book_linked_quote_number,
    dynamic book_linked_quote_section_id,
    String? book_linked_quote_section_name,
    bool? book_is_linked_quote_declined,
    bool? book_is_back_costing_link_available,
    CostSummary? cost_summary,
    String? bookcont_acceptance_status_name,
    @Default(true) bool book_client_contact_id_specified,
    @Default(true) bool book_job_id_specified,
    @Default(true) bool book_site_contact_id_specified,
    @Default(true) bool book_recurrence_pattern_specified,
    @Default(false) bool book_has_files,
    @Default(false) bool book_has_notes,
    @Default(false) bool book_has_photos,
    @Default(false) bool book_has_scribbles,
    String? book_bookingstatus_change_location,
  }) = _TaskInfoLevelModel;

  factory TaskInfoLevelModel.fromJson(Map<String, Object?> json) =>
      _$TaskInfoLevelModelFromJson(json);
}

@freezed
class BookingContact with _$BookingContact {
  const factory BookingContact({
    int? bookcont_id,
    int? bookcont_book_id,
    int? bookcont_contact_id,
    String? bookcont_contact_initials,
    String? bookcont_contact_name_display,
    String? bookcont_contact_name_business,
    bool? bookcont_contact_is_access_disabled,
    String? bookcont_contact_brush_colour_argb,
    String? bookcont_contact_email,
    dynamic bookcont_contact_phone_mobile,
    String? bookcont_acceptance_status,
    String? bookcont_acceptance_status_name,
    String? bookcont_acceptance_comment,
    dynamic bookcont_bookingstatus_id,
    String? bookcont_bookingstatus_name,
    String? bookcont_contacttype_name,
    String? bookcont_bookingstatus_brush_colour_argb,
    bool? is_current_subscriber,
    bool? bookcont_contact_is_user,
  }) = _BookingContact;

  factory BookingContact.fromJson(Map<String, Object?> json) =>
      _$BookingContactFromJson(json);
}
