name: api_service
description: Dart package which manages the api endpoints for nextminute.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.3.10'

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  # equatable: ^2.0.5
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  flutter_timezone: ^1.0.4

  hive: ^2.2.3

  intl: ^0.18.0

  json_annotation: ^4.7.0
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner:
  freezed: ^2.2.1

  hive_generator:

  json_serializable: ^6.5.4

  flutter_test:
    sdk: flutter
