name: nextminute

on: [pull_request, push]

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      min_coverage: 80
      coverage_excludes: 'lib/app/view/app_router.gr.dart'
      flutter_channel: stable
      flutter_version: 3.3.7
